name: 'Shift-Left Security Scans'

on:
  push:
    branches:
      - main
      - master

jobs:
  security-scans:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run SAST Scan (Semgrep with Docker)
        run: |
          docker run --rm -v "$(pwd):/src" returntocorp/semgrep:latest \
          semgrep scan --output /src/sast_before.json --json --config "auto" /src

      - name: Run SCA Scan (OWASP Dependency-Check with Docker)
        run: |
          # Create a report directory and give it open permissions
          mkdir -p ./dependency-check-reports
          chmod 777 ./dependency-check-reports
          
          # Run the container with increased memory and the new report volume
          docker run --rm \
            -e DC_OPTS="-Xmx6g" \
            -v "$(pwd):/src" \
            -v "$(pwd)/dependency-check-reports:/report" \
            owasp/dependency-check:latest \
            --disableArchive \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --scan /src \
            --format HTML \
            --out /report
      
      - name: Rename SCA Report
        run: mv ./dependency-check-reports/dependency-check-report.html ./dependency_before.html

      - name: Upload Scan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-scans-before
          path: |
            sast_before.json
            dependency_before.html
