name: 'Shift-Left Security Scans'
on:
  push:
    branches:
      - main
      - master
jobs:
  security-scans:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Run SAST Scan (Semgrep)
        uses: semgrep/semgrep-action@v2
        with:
          command: scan --output sast_before.json --json --config "auto" .
      - name: Run SCA Scan (OWASP Dependency-Check)
        uses: dependency-check/scan-action@v5
        with:
          scan: '.'
          format: 'HTML'
          output: './dependency-check-reports'
          fail: false
      - name: Rename SCA Report
        run: mv ./dependency-check-reports/dependency-check-report.html ./dependency_before.html
      - name: Upload Scan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-scans-before
          path: |
            sast_before.json
            dependency_before.html
